import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

# Bit mask for the left mouse button inside the HID "buttons" byte.
LEFT_BUTTON_MASK = 0x01
# Output image holding the reconstructed drawing.
OUT_PATH = "usb_hid_path.png"

# Load the CSV generated by extract_usb_hid.sh (or similar pipeline).
df = pd.read_csv("usb_hid_events.csv")
# Identify samples where the left button was held down (pen touching the canvas).
pressed = (df["buttons"] & LEFT_BUTTON_MASK) != 0

# Replace coordinates with NaN while the button is released so Matplotlib
# automatically breaks the polyline between strokes (avoids ghost segments).
x = df["x"].where(pressed, np.nan)
y = df["y"].where(pressed, np.nan)

# Reconstruct the cursor path with the origin flipped to match the desktop coordinates.
plt.plot(x, y, linewidth=1)
plt.gca().invert_yaxis()
plt.axis("equal")
plt.title("USB HID Mouse Path (left button strokes)")
plt.savefig(OUT_PATH, dpi=200, bbox_inches="tight")
plt.close()
print(f"Plot saved to {OUT_PATH}")
